name = "airplane-performance-cloudflare"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-20"

[vars]
NATE_ENV_VAR = "foo bar"

[build]
# command = "cargo install -q worker-build && worker-build --release" # required
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
